language: node.js
node.js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn test --wacthAll=false
  - yarn build
on:
  branch: master
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: $HEROKU_APP